#!/bin/bash

while [ ! $# -eq 0 ]
do
	case "$1" in
		--bucket | -b)
			BUCKET="$2"
			;;
		--region)
			REGION="$2"
			;;
		--lambda | -l)
			LAMBDA_NAME="$2"
			;;
		--role)
			ROLE_ARN="$2"
			;;
	esac
	shift
done
